#################################################---START INPUT DATA---#######################################################

# List of accessions file
Accession_list: Configure/Input_Data/229E_full_accession_list.txt
date_corrections : Configure/Input_Data/extra_229E_accessions_metadata.json

# Reference genbanks
Reference_genbank: Configure/Input_Data/HcoV-229E_referance_sequence.gb
Reference_accession: NC_002645

# Outgroup for rooting tree
Outgroup: camel_Riyadh_Ry141_2015_NC_028752_2015-03-XX 

# Size threshold filters
# HcoV-229E genome is ~27kb
# HcoV-229E spike protein is ~ 3450
Genome_size_threshold_lower: 1500
Genome_size_threshold_upper: 28000
# Minimum size ORF when translating to HcoV-229E spike protein
# is ~ 3.4kb
# ORF minumum size
ORF_min_size:
  spike: 3450 

# Maximum fraction of ambiuous bases allowed
max_frac_N: 
  genes: 0

# Remove duplicates 'Yes' or 'No'
Remove_duplicates: 'No'

# Sequences to remove
Accessions_to_exclude: 
  - JX503061 # outlier on date-to-tip regression
  - KY674919 # outlier on date-to-tip regression
  - AF344186 # outlier on date-to-tip regression
  - PQ243243 # outlier on date-to-tip regression
  - KY073748 # related-bat-229E
  - DQ243963 # ATCC-VR740 propagated in MRC-5 cells
  - AB691763 # ATCC-VR740 from https://www.microbiologyresearch.org/content/journal/jgv/10.1099/vir.0.043117-0#tab2
  - KF293666 # ATCC-VR740 passage 10 from https://pmc.ncbi.nlm.nih.gov/articles/PMC4038610/
  - KF293664 # ATCC-VR740 from https://pmc.ncbi.nlm.nih.gov/articles/PMC4038610/
  - KF293665 # ATCC-VR740 mock from https://pmc.ncbi.nlm.nih.gov/articles/PMC4038610/
  - OK662398 # ATCC-VR740 propagated in MRC-5 cells
  - OK625404 # ATCC-VR740 propagated in MRC-5 cells
  - AF344189 # from persistently infected L-132 cells
  - AF344187 # from persistently infected L-132 cells
  - AF344188 # from persistently infected L-132 cells
  - AF304460 # duplicated with reference sequence 

# Sequences to make sure are included
Accessions_to_include:
  - NC_028752
  - NC_002645
  - DQ243972
  - DQ243976
  - DQ243977
  - KM055556
  - KY369909
  - JX503060
  - MF542265
  - AB691765
  - AB691767
  - AB691764
  - AB691766


# Sequences of strains that were pseudotyped in previous study 
Accessions_from_pre_study:
  - DQ243972
  - DQ243976
  - DQ243977
  - KM055556
  - KY369909 

# Gene name groupings
Gene_groupings:
  spike:
    - S # reference label
    - SPIKE
    - SPIKE PROTEIN
    - SPIKE GLYCOPROTEIN
    - spike protein
    - S glycoprotein
    - Spike glycoprotein
    - spike glycoprotein
    - spike
    - glycoprotein
    - surface glycoprotein
    - G
    - G PROTEIN
    - attachment glycoprotein
    - G protein
    - HA
    - S PROTEIN


# Auspice configuration
Auspice_config: Configure/Input_Data/auspice_config.json
Color_schemes: Configure/Input_Data/color_schemes.tsv
Color_orderings: Configure/Input_Data/color_orderings.tsv
Lat_longs: Configure/Input_Data/lat_longs.tsv

# Antibody escape data:
Antibody_escape_file: Configure/Input_Data/filtered_APN_binding.csv
Antibody_names:
  APN: APN
Site_map: Configure/Input_Data/site_numbering_map.csv
# Antibody escape prediction parameters
Antibody_escape_prediction_params:
  Reference_DMS_strain: "HCoV-229E-5_9_84_DQ243972_2016-07-26" # name of reference DMS strain
  Mut_effect_col: "escape" # name of the column containing the effect score
  Mutation_col: "natural_sequence_mutation" # name of the column containing the mutation
  Antibody_escape_filter_params: null

Auspice_tree_titles:
  spike: "'hCoV 229E phylogentic tree'"

Auspice_tree_descriptions:
  spike: Configure/Input_Data/spike_description.md

#################################################---END INPUT DATA---#########################################################

#################################################---START DATA GROUPINGS---###################################################

Asia:
  - Israel
  - Lebanon
  - Jordan
  - Syria
  - Georgia
  - Iraq
  - Armenia
  - Saudi Arabia
  - Kuwait
  - Yemen
  - Bahrain
  - Qatar
  - Iran
  - United Arab Emirates
  - Oman
  - Uzbekistan
  - Afghanistan
  - Kazakhstan
  - Pakistan
  - Tajikistan
  - Maldives
  - Kyrgyzstan
  - India
  - Sri Lanka
  - Nepal
  - Asia
  - Bangladesh
  - Myanmar
  - Thailand
  - Malaysia
  - Mongolia
  - Laos
  - Singapore
  - China
  - Cambodia
  - Vietnam
  - Hong Kong
  - Indonesia
  - Brunei
  - Taiwan
  - Philippines
  - Timor-Leste
  - South Korea
  - Japan

Oceania:
  - French Polynesia
  - Palau
  - Australia
  - Papua New Guinea
  - Oceania
  - Micronesia
  - Solomon Islands
  - Vanuatu
  - Marshall Islands
  - New Zealand
  - Kiribati
  - Fiji

Africa:
  - Cabo Verde
  - Gambia
  - Guinea-Bissau
  - Senegal
  - Sierra Leone
  - Guinea
  - Liberia
  - Mauritania
  - Côte d'Ivoire
  - Morocco
  - Mali
  - Burkina Faso
  - Ghana
  - Togo
  - Benin
  - Algeria
  - Sao Tome and Principe
  - Nigeria
  - Tunisia
  - Niger
  - Equatorial Guinea
  - Gabon
  - Cameroon
  - Republic of the Congo
  - Libya
  - Namibia
  - Angola
  - Chad
  - Central African Republic
  - Democratic Republic of the Congo
  - Africa
  - Botswana
  - South Africa
  - Zambia
  - Lesotho
  - Sudan
  - South Sudan
  - Zimbabwe
  - Burundi
  - Rwanda
  - Egypt
  - Eswatini
  - Uganda
  - Malawi
  - Mozambique
  - Tanzania
  - Kenya
  - Ethiopia
  - Djibouti
  - Union of the Comoros
  - Madagascar
  - Somalia
  - Seychelles
  - Mauritius

Europe:
  - Iceland
  - Portugal
  - Ireland
  - Spain
  - United Kingdom
  - Andorra
  - France
  - Belgium
  - Netherlands
  - Luxembourg
  - Monaco
  - Switzerland
  - Norway
  - Denmark
  - Liechtenstein
  - Germany
  - Europe
  - Italy
  - Malta
  - Slovenia
  - Sweden
  - Austria
  - Croatia
  - Czech Republic
  - Bosnia and Herzegovina
  - Poland
  - Slovakia
  - Montenegro
  - Albania
  - Hungary
  - Serbia
  - Kosovo
  - North Macedonia
  - Greece
  - Lithuania
  - Romania
  - Bulgaria
  - Latvia
  - Estonia
  - Finland
  - Belarus
  - Moldova
  - Ukraine
  - Cyprus
  - Turkey
  - Azerbaijan
  - Russia

South America:
  - Argentina
  - Uruguay
  - Chile
  - Paraguay
  - Bolivia
  - South America
  - Brazil
  - Peru
  - Ecuador
  - Colombia
  - Suriname
  - Guyana
  - Venezuela
  - Trinidad and Tobago
  - Bonaire
  - Curacao
  - Aruba

North America:
  - Panama
  - Costa Rica
  - Grenada
  - Nicaragua
  - Saint Vincent and the Grenadines
  - Barbados
  - El Salvador
  - Saint Lucia
  - Honduras
  - Dominica
  - Guatemala
  - Guadeloupe
  - Belize
  - Antigua and Barbuda
  - Saint Kitts and Nevis
  - Saint Barthélemy
  - Sint Maarten
  - Saint Martin
  - Jamaica
  - Dominican Republic
  - Haiti
  - Mexico
  - Cuba
  - Bahamas
  - North America
  - Bermuda
  - USA
  - Canada

#################################################---END DATA GROUPINGS---#####################################################

#################################################---START GENBANK FEATURES---#################################################

Genbank_features:
  - assembly_gap
  - C_region
  - CDS
  - centromere
  - D-loop
  - D_segment
  - exon
  - gap
  - gene
  - iDNA
  - intron
  - J_segment
  - mat_peptide
  - misc_binding
  - misc_difference
  - misc_feature
  - misc_recomb
  - misc_RNA
  - misc_structure
  - mobile_element
  - modified_base
  - mRNA
  - ncRNA
  - N_region
  - old_sequence
  - operon
  - oriT
  - polyA_site
  - precursor_RNA
  - prim_transcript
  - primer_bind
  - propeptide
  - protein_bind
  - regulatory
  - repeat_region
  - rep_origin
  - rRNA
  - S_region
  - sig_peptide
  - source
  - stem_loop
  - STS
  - telomere
  - tmRNA
  - transit_peptide
  - tRNA
  - unsure
  - V_region
  - V_segment
  - variation
  - 3'UTR
  - 5'UTR

#################################################---END GENBANK FEATURES---###################################################
#################################################---START HOST GROUPINGS---###################################################

# Adapted from https://animaldiversity.org
Host_grouper:
  Human:
    - homo sapiens
    - humans
    - human
    - patient


#################################################---END HOST GROUPINGS---#####################################################